testk: ENC[AES256_GCM,data:UOZKhLg=,iv:pgaazUXl9JQg2q6b/RSfTxa7xhGHo7u5D7HoqCE5C2I=,tag:jGYMx/PffUYZtRQkRBl6Bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-27T10:25:49Z"
    mac: ENC[AES256_GCM,data:6kzDS9QzySDm70/G7HwywW5zgJ4CKcL4VBm+87i+DhwVczs6B/G1wHadeKfUL0OOLJQQrW8tUI54PejRsX5JOogD6lXeaxIHCaplXOKYTyVzSjcqGqsAF9aLcUfwWDSBMo2Q5BZzh1HAGPtb6hi7JexLMtRPrF9eRElNPSNXIGE=,iv:sqtggxja83jRNFbFQIOrplYBpDCgk+NJtnLBPGaaZQA=,tag:4EPmyqvXanWIJSvCoOIgvQ==,type:str]
    pgp:
        - created_at: "2021-07-27T10:25:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+h47nGcE/LKAQf/crETZpZV+NEyf2e6ryibOG3zKJ3wNxVLugHl++m39NV5
            UumgGAHE/Arelhb3DpAJdPNEcBMfMW89QfKrbkvrD9IrMRlci2PWTWXWMz/FEm+8
            pOXbHd38nhCZ5ua4zawT0w6Q4G2T8KvXEHGt54maL12Wuznat2ehkGR451WOkXA5
            r5cs9NwDcuoyp/j8+lWQRZQHbryLRONbNCgs1ptyk+FPa+M8wnmSATbdTGoQpJT4
            USSewjcBsSe+g77aMD4dDJDxl4Q0ve0WucmSfUZewigi+X6KOVHUQvRJOErlSetI
            To5cqY+wzofG9KFpkG/HCbGnCAKatSC8V1ifBLVjYtJeAQoJPDZIWDp+CImRU/z0
            XdalETdC1yY0U7oRazMI1VgjVE6lpDsNQfXImGs9NdBlIeK2po5Zk9Obzgajvy0q
            vAWbbTMUTBRsDDBcKjE+sfAEiUqJgyTmhGVlYVgm1Q==
            =jt25
            -----END PGP MESSAGE-----
          fp: 327B98529448C65CBC7FEF3FB29B13C64673339B
    unencrypted_suffix: _unencrypted
    version: 3.7.1
