# permissions for end users to view tangservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tangserver-viewer-role
rules:
- apiGroups:
  - daemons.sarroutbi
  resources:
  - tangservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - daemons.sarroutbi
  resources:
  - tangservers/status
  verbs:
  - get
