apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: tang-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: TangServer is the Schema for the tangservers API
      displayName: Tang Server
      kind: TangServer
      name: tangservers.daemons.redhat.com
      version: v1alpha1
  description: Tang Operator for NBDE
  displayName: tang
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - tang
  - nbde
  links:
  - name: Tang Operator
    url: https://tang-operator.domain
  maintainers:
  - email: scorreia@redhat.com
    name: Sergio Correia
  - email: sarroutb@redhat.com
    name: Sergio Arroutbi
  maturity: alpha
  provider:
    name: Red Hat Inc
  version: 0.0.0
