apiVersion: daemons.redhat/v1alpha1
kind: TangServer
metadata:
  name: tangserver
spec:
  # Add fields here
  keypath: /var/db
  keyamount: 2
  replicas: 3
#  image: "rhel8/tang"
  image: "sarroutbi/fedora_tang"
  version: "v0.0.3"
#  version: "1": "latest" by default. Adjust in case neccessary
