name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup OpenShift
      uses: manusa/actions-setup-openshift@v1.1.3
      with:
        oc version: 'v4.8.2'
        github token: ${{secrets.GITHUB_TOKEN}}

    - name: Build
      run: make

    - name: Test
      run: make test
