name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master

    - name: Status
      run: minikube status

    - name: Download operator-sdk
      uses: sarroutbi/operator-sdk-github-action@v1.0.3-alpha4
      with:
        image: "tang-operator"
        tag: v0.0.11
        dirPath: "./"
        operatorSdkReleaseVersion: "v1.8.2"
      
    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Deploy
      run: /operator-sdk run bundle --timeout 5m quay.io/sarroutb/tang-operator-bundle:v0.0.11
      
      
