name: Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Minikube Installation
      id: minikube
      uses: sarroutbi/setup-minikube@master

    - name: Status
      run: minikube status

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Deploy
      run: sh .github/workflows/scripts/retrieve_and_run_operator_sdk.sh "v1.10.1" "quay.io/sarroutb/tang-operator-bundle:v0.0.11" "10m"
