name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master

    - name: kubectl
      uses: kubectl get pods
      
    - name: Build
      run: make

    - name: Test
      run: make test
